apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      initContainers:
        - name: init-filestore
          image: busybox:1.28
          command: ["sh", "-c", "chmod og+w /mnt/criticalvolume/redis"]
          volumeMounts:
            - mountPath: /mnt/criticalvolume
              name: criticalvolume
      containers:
        - name: redis
          image: "docker.io/redis:6.0.5"
          args: ["--appendonly", "yes", "--save", "30", "1"]
          workingDir: /mnt/criticalvolume/redis
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /mnt/criticalvolume
              name: criticalvolume
      volumes:
        - name: criticalvolume
          persistentVolumeClaim:
            claimName: criticalvolume-claim
            readOnly: false
