apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbinia-worker-loadtest
  labels:
    app: turbinia-worker-loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbinia-worker-loadtest
  template:
    metadata:
      annotations:
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
      labels:
        app: turbinia-worker-loadtest
    spec:
      # The grace period needs to be set to the largest task timeout as
      # set in the turbinia configuration file.
      terminationGracePeriodSeconds: 86400
      initContainers:
        - name: init-filestore
          image: busybox:1.28
          command: ["sh", "-c", "chmod go+w /mnt/criticalvolume"]
          volumeMounts:
            - mountPath: "/mnt/criticalvolume"
              name: criticalvolume
      containers:
        - name: worker
          #image: us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-ng-worker-dev:latest
          image: rbdebeer/turbinia-worker-dev
          command: ["sh", "-c", "tail -f /dev/null"]
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "touch /tmp/turbinia-to-scaledown.lock && sleep 5 && /usr/bin/python3 /tmp/k8s/tools/check-lockfile.py"
          securityContext:
            privileged: true
          env:
            - name: TURBINIA_CONF
              valueFrom:
                configMapKeyRef:
                  name: turbinia-config
                  key: TURBINIA_CONF
            - name: TURBINIA_EXTRA_ARGS
              value: "-d"
          volumeMounts:
            - mountPath: /mnt/criticalvolume
              name: criticalvolume
            - mountPath: "/dev"
              name: dev
              readOnly: true
            - mountPath: "/var/run/lock"
              name: lockfolder
              readOnly: false
          ports:
            - containerPort: 9200
          resources: #TODO adjust for GKE
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "8192Mi"
              cpu: "32000m"
      volumes:
        - name: criticalvolume
          persistentVolumeClaim:
            claimName: criticalvolume-claim
            readOnly: false
        - name: dev
          hostPath:
            path: /dev
        - name: lockfolder
          hostPath:
            path: /var/run/lock
