language: python
python:
  - '3.6'
cache:
  - pip

install:
  - pip install mock nose coverage yapf
  - pip install tox
  - pip install .
  - pip install .[local]
  - pip install -r dfvfs_requirements.txt

script:
  - cp ./test_data/.turbiniarc ~/
  - ./run_tests.py
  - tox --sitepackages ${TOXENV}
