version: "3.2"
services:
    redis:
        image: "redis:alpine"
        command: redis-server
        # This will *only* expose it to the docker network, not to the host.
        # See https://docs.docker.com/compose/compose-file/compose-file-v3/#expose
        expose:
            - "6379"
        volumes:
            - $PWD/redis-data:/var/lib/redis
        environment:
            - REDIS_REPLICATION_MODE=master

    turbinia-server:
        build:
          context: ../../
          dockerfile: docker/server/Dockerfile
        image: "turbinia-server:dev" # Use this for local development and comment out below line
        #image: "us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-server:latest" # Latest stable
        container_name: turbinia-server
        depends_on:
            - redis
        volumes:
            - $PWD/evidence:/evidence
            - $PWD/conf/turbinia.conf:/etc/turbinia/turbinia.conf
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - TURBINIA_EXTRA_ARGS=${TURBINIA_EXTRA_ARGS}

    turbinia-api-server:
        build:
          context: ../../
          dockerfile: docker/api_server/Dockerfile
        image: "turbinia-api-server:dev" # Use this for local development and comment out below line
        #image: "us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-api-server:latest" # Latest stable
        container_name: turbinia-api-server
        depends_on:
            - redis
        volumes:
            - $PWD/evidence:/evidence
            - $PWD/conf/turbinia.conf:/etc/turbinia/turbinia.conf
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - TURBINIA_EXTRA_ARGS=${TURBINIA_EXTRA_ARGS}
        expose:
            - "8000"

    turbinia-worker:
        build:
          context: ../../
          dockerfile: docker/worker/Dockerfile
        image: "turbinia-worker:dev" # Use this for local development and comment out below line
        #image: "us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-worker:latest" # Latest stable
        container_name: turbinia-worker
        privileged: true
        depends_on:
            - redis
        volumes:
            - $PWD/evidence:/evidence
            - $PWD/conf/turbinia.conf:/etc/turbinia/turbinia.conf
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - TURBINIA_EXTRA_ARGS=${TURBINIA_EXTRA_ARGS}
        develop:
          watch:
            - action: sync+restart
              path: ../../turbinia/workers
              target: /home/turbinia/turbinia/workers

    # Uncomment below in case you want to run a second worker on the same host.
    #  turbinia-worker2:
    #     image: "turbinia-worker-dev" # Use this for local development and comment out below line
    #     image: "us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-worker:latest" # Latest stable
    #     container_name: turbinia-worker2

    #     volumes:
    #      - $PWD/evidence:/evidence
    #      - $PWD/conf/turbinia.conf:/etc/turbinia/turbinia.conf

    #     environment:
    #      - LC_ALL=C.UTF-8
    #      - LANG=C.UTF-8
    #      - TURBINIA_EXTRA_ARGS=${TURBINIA_EXTRA_ARGS}
