global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
      environment: turbinia-gcp_node

scrape_configs:
  - job_name: 'turbinia-gcp'
    gce_sd_configs:
        # The GCP Project
        - project: '<project>'
          zone: '<zone>'
          filter: labels.turbinia-prometheus=true
          refresh_interval: 120s
          port: 9100
  - job_name: 'turbinia-app'
    gce_sd_configs:
        # The GCP Project
        - project: '<project>'
          zone: '<zone>'
          filter: labels.turbinia-prometheus=true
          refresh_interval: 120s
          port: 9200