apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: criticalvolume-claim
spec:
  # Specify "" as the storageClassName so it matches the PersistentVolume's StorageClass.
  # A nil storageClassName value uses the default StorageClass. For details, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: criticalvolume
  resources:
    requests:
      storage: 10G