apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbinia-server
  labels:
    app: turbinia-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turbinia-server
  template:
    metadata:
      annotations:
        prometheus.io/port: "9200"
        prometheus.io/scrape: "true"
      labels:
        app: turbinia-server
    spec:
      initContainers:
        - name: init-filestore
          image: busybox:1.28
          command: ['sh', '-c', 'chmod go+w /mnt/turbiniavolume']
          volumeMounts:
            - mountPath: "/mnt/turbiniavolume"
              name: turbiniavolume
      containers:
        - name: server
          image: us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-server:latest
          env:
            - name: TURBINIA_CONF
              valueFrom:
                configMapKeyRef:
                  name: turbinia-config
                  key: TURBINIA_CONF
            - name: TURBINIA_EXTRA_ARGS
              value: "-d"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /mnt/turbiniavolume
              name: turbiniavolume
          ports:
            - containerPort: 9200
      volumes:
        - name: turbiniavolume
          persistentVolumeClaim:
            claimName: turbiniavolume-claim
            readOnly: false