# Google Cloud Build configuration for Turbinia worker release
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-worker:$TAG_NAME",
        "-t",
        "us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-worker:latest",
        "--build-arg",
        "PPA_TRACK=${_PPA_TRACK}",
        "-f",
        "docker/worker/Dockerfile",
        ".",
      ]
    timeout: 4800s
timeout: 4800s
images:
  - us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-worker:latest
  - us-docker.pkg.dev/osdfir-registry/turbinia/release/turbinia-worker:$TAG_NAME
